[pytest]
norecursedirs = *.egg .eggs dist build docs .tox
pythonpath = .
filterwarnings =
    once::DeprecationWarning
    once::PendingDeprecationWarning
addopts = -v --tb=short --maxfail=10 --durations=10 --ignore=tests/query_runner/test_e6data.py --ignore=tests/query_runner/test_trino.py --ignore=tests/query_runner/test_influx_db.py --ignore=tests/query_runner/test_influx_db_v2.py --ignore=tests/query_runner/test_google_spreadsheets.py --ignore=tests/query_runner/test_duckdb.py --ignore=tests/query_runner/test_bigquery.py --ignore=tests/query_runner/test_mongodb.py --ignore=tests/query_runner/test_oracle.py --ignore=tests/query_runner/test_azure_kusto.py --ignore=tests/query_runner/test_ignite.py --ignore=tests/query_runner/test_databricks.py
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(name)s: %(message)s
